### ISSUE TITLE
Hyprspace clone?

### ISSUE THREAD

**Issue by mrbluecoat** [mudler/edgevpn#1]
Thoughts about combining efforts with [Hyprspace](https://github.com/hyprspace/hyprspace/)? At a glance, appears to have a lot of overlap..

**Comment by mudler** [comment]
Hi, I didn't know about Hyprsprace, and indeed projects seems similar, but having a look at the code they seems to be a bit different. 

Altought, if you look at it edgevpn was published on May, so somehow seems both project started on the same period more or less (Hyprsprace in june).

Anyhow, edgevpn can be used likely as a library, and allow more customization on top, that's what I've been using it personally for and couldn't find an alternative since. By looking at Hyprsprace, I think I'll keep edgevpn around for a while

**Comment by dukzcry** [comment]
@mrbluecoat edgevpn has web interface and windows support which is cool. Also just now I had a case where hyprspace wasn't able to create a connection, while edgevpn had no problem with it.
